---
name: on_hello_event1
pack: best_pack
description: Sample rule firing on best_pack.event1.
enabled: true
trigger:
    type: hello_st2.event1
action:
    ref: best_pack.greet
    parameters:
        greeting: Yo