---
name: on_hello_event1
pack: best_pack
description: Sample rule firing on best_pack.event1.
enabled: true
trigger:
    type: robot_pack.event1
action:
    ref: robot_pack.the_test
    parameters:
        greeting: Yo